#!/usr/bin/env python3
"""
Generate idempotent seed SQL for vocab_cards from vocab_enriched.json.

The seed is:
  • Repeatable — can be run multiple times safely
  • Idempotent — uses ON CONFLICT (word) DO NOTHING
  • Validated — checks for duplicates before generating
  • Safe against duplicates — ON CONFLICT prevents duplicate inserts

Usage:
  python supabase/seeds/generate_seed.py

Output:
  supabase/seeds/seed_vocab_cards.sql
"""

import json
import os
from pathlib import Path

# ── Paths ─────────────────────────────────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent.parent.parent
INPUT_FILE = BASE_DIR / "data" / "seed" / "vocab_enriched.json"
OUTPUT_FILE = Path(__file__).resolve().parent / "seed_vocab_cards.sql"

# ── Valid values ─────────────────────────────────────────────────────
VALID_CEFR = {"A1", "A2", "B1", "B2", "C1", "C2"}
VALID_EXAMS = {"TOEIC", "IELTS", "TOEFL", "VSTEP"}


def escape_sql_string(s: str) -> str:
    """Escape single quotes for SQL string literals."""
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


def format_text_array(value: str) -> str:
    """Format a single exam_type string as a PostgreSQL text array literal."""
    if not value:
        return "'{}'"
    # Handle comma-separated or single values
    parts = [v.strip() for v in str(value).split(",") if v.strip()]
    if not parts:
        return "'{}'"
    inner = ",".join(f'"{p}"' for p in parts)
    return "'{" + inner + "}'"


def validate_entry(entry: dict, idx: int) -> list[str]:
    """Validate a single vocab entry. Returns list of errors."""
    errors = []
    word = entry.get("word")
    if not word or not str(word).strip():
        errors.append(f"Row {idx}: missing 'word'")
    meaning_en = entry.get("meaning_en")
    if not meaning_en or not str(meaning_en).strip():
        errors.append(f"Row {idx} ({word}): missing 'meaning_en'")
    meaning_vi = entry.get("meaning_vi")
    if not meaning_vi or not str(meaning_vi).strip():
        errors.append(f"Row {idx} ({word}): missing 'meaning_vi'")
    cefr = entry.get("difficulty_level")
    if cefr and cefr not in VALID_CEFR:
        errors.append(f"Row {idx} ({word}): invalid CEFR level '{cefr}'")
    exam = entry.get("exam_type")
    if exam:
        for e in str(exam).split(","):
            e = e.strip()
            if e and e not in VALID_EXAMS:
                errors.append(f"Row {idx} ({word}): invalid exam type '{e}'")
    return errors


def format_synonym_field(value) -> str:
    """Format synonym/antonym field for SQL.
    The enriched data has lists; the canonical schema has text.
    We join list items with ', '.
    """
    if value is None:
        return "NULL"
    if isinstance(value, list):
        if len(value) == 0:
            return "NULL"
        joined = ", ".join(str(v) for v in value)
        return escape_sql_string(joined)
    return escape_sql_string(str(value))


def generate_seed():
    """Generate the seed SQL file."""
    # Load data
    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)

    print(f"Loaded {len(data)} entries from {INPUT_FILE}")

    # Validate
    all_errors = []
    seen_words = set()
    for i, entry in enumerate(data):
        all_errors.extend(validate_entry(entry, i))
        word = entry.get("word", "")
        if word in seen_words:
            all_errors.append(f"Row {i}: duplicate word '{word}'")
        seen_words.add(word)

    if all_errors:
        print("VALIDATION ERRORS:")
        for e in all_errors[:20]:
            print(f"  {e}")
        if len(all_errors) > 20:
            print(f"  ... and {len(all_errors) - 20} more")
        raise SystemExit(1)

    print("Validation passed — no errors")

    # Generate SQL
    lines = [
        "-- ─────────────────────────────────────────────────────────────────────",
        "-- seed_vocab_cards.sql — Idempotent vocabulary seed data",
        "-- ─────────────────────────────────────────────────────────────────────",
        "-- Auto-generated by supabase/seeds/generate_seed.py",
        f"-- Source: data/seed/vocab_enriched.json ({len(data)} records)",
        "--",
        "-- This seed is IDEMPOTENT:",
        "--   • Uses ON CONFLICT (word) DO NOTHING — safe to run multiple times",
        "--   • Existing words are NOT overwritten",
        "--   • New words are inserted",
        "--",
        "-- Run AFTER all schema migrations (001–011).",
        "-- ─────────────────────────────────────────────────────────────────────",
        "",
    ]

    # Batch insert in chunks of 500 for readability and performance
    BATCH_SIZE = 500
    for batch_start in range(0, len(data), BATCH_SIZE):
        batch = data[batch_start:batch_start + BATCH_SIZE]
        lines.append(
            f"-- Batch {batch_start // BATCH_SIZE + 1} "
            f"(rows {batch_start + 1}–{batch_start + len(batch)})"
        )
        lines.append(
            "insert into vocab_cards "
            "(word, phonetic, synonym, antonym, meaning_en, meaning_vi, "
            "example_sentence, exam_type, cefr_level, category) values"
        )

        value_lines = []
        for entry in batch:
            word = escape_sql_string(entry.get("word", ""))
            phonetic = escape_sql_string(entry.get("phonetic"))
            synonym = format_synonym_field(entry.get("synonym"))
            antonym = format_synonym_field(entry.get("antonym"))
            meaning_en = escape_sql_string(entry.get("meaning_en", ""))
            meaning_vi = escape_sql_string(entry.get("meaning_vi", ""))
            example = escape_sql_string(entry.get("example_sentence"))
            exam_type = format_text_array(entry.get("exam_type", ""))
            cefr = escape_sql_string(entry.get("difficulty_level"))
            if cefr == "NULL":
                cefr = "NULL"
            category = escape_sql_string(entry.get("category", "general"))
            if category == "NULL":
                category = "'general'"

            value_lines.append(
                f"  ({word}, {phonetic}, {synonym}, {antonym}, "
                f"{meaning_en}, {meaning_vi}, {example}, "
                f"{exam_type}, {cefr}, {category})"
            )

        lines.append(",\n".join(value_lines))
        lines.append("on conflict (word) do nothing;")
        lines.append("")

    # Footer
    lines.append("-- ── End of seed ──────────────────────────────────────────────────")

    # Write
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Generated {OUTPUT_FILE}")
    print(f"  {len(data)} records in {(len(data) + BATCH_SIZE - 1) // BATCH_SIZE} batches")


if __name__ == "__main__":
    generate_seed()
