-- ─────────────────────────────────────────────────────────────────────
-- migrate_user_data.sql — Migrate user data from original SQLite DB
-- ─────────────────────────────────────────────────────────────────────
-- Generated by scripts/restore_original_content.py
-- Source: data.db from git commit 98321ac
-- Generated: 2026-08-31T17:17:54.542350+00:00
--
-- This migration is IDEMPOTENT:
--   • Uses ON CONFLICT DO NOTHING for sessions and plans
--   • Uses ON CONFLICT DO UPDATE for vocab_progress (upsert)
--
-- PREREQUISITE: The user must already exist in auth.users.
--   Map original user_id=1 to the Supabase auth user by setting
--   :target_user_id below or running after authentication.
-- ─────────────────────────────────────────────────────────────────────

-- Replace :target_user_id with the actual Supabase auth user UUID
-- Example: do $$ begin
--   :target_user_id := 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx';
-- end $$;

-- Original user: id=1, name=Phat, target_exam=IELTS, target_score=9.0

-- ─── Vocabulary Progress (SRS State) ───
-- Maps original card_id → word → Supabase vocab_cards.id

-- Word: 'was' (original card_id=1)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('was')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'have' (original card_id=2)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('have')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'not' (original card_id=3)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('not')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'all' (original card_id=4)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('all')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'can' (original card_id=5)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('can')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'will' (original card_id=6)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('will')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'just' (original card_id=7)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('just')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'like' (original card_id=8)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('like')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'about' (original card_id=9)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('about')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'out' (original card_id=10)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('out')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'has' (original card_id=11)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('has')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'more' (original card_id=12)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('more')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'were' (original card_id=13)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('were')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'had' (original card_id=14)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('had')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'there' (original card_id=15)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('there')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'time' (original card_id=16)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('time')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'been' (original card_id=17)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('been')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'new' (original card_id=18)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('new')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'people' (original card_id=19)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('people')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'also' (original card_id=20)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('also')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'now' (original card_id=21)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('now')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'other' (original card_id=22)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('other')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'good' (original card_id=23)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('good')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'only' (original card_id=24)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('only')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'after' (original card_id=25)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('after')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'first' (original card_id=26)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('first')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'know' (original card_id=27)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('know')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'see' (original card_id=28)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('see')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'two' (original card_id=29)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('two')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'make' (original card_id=30)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('make')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'over' (original card_id=31)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('over')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'think' (original card_id=32)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('think')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'any' (original card_id=33)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('any')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'then' (original card_id=34)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('then')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'back' (original card_id=35)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('back')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'want' (original card_id=36)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('want')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'well' (original card_id=37)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('well')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'said' (original card_id=38)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('said')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'way' (original card_id=39)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('way')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'most' (original card_id=40)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('most')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'much' (original card_id=41)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('much')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'very' (original card_id=42)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('very')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'even' (original card_id=43)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('even')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'may' (original card_id=44)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('may')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'here' (original card_id=45)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('here')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'need' (original card_id=46)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('need')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'really' (original card_id=47)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('really')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'right' (original card_id=48)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('right')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'work' (original card_id=49)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('work')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'year' (original card_id=50)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('year')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'being' (original card_id=51)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('being')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'day' (original card_id=52)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('day')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'too' (original card_id=53)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('too')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'going' (original card_id=54)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('going')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'before' (original card_id=55)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('before')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'off' (original card_id=56)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('off')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'why' (original card_id=57)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('why')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'made' (original card_id=58)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('made')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'still' (original card_id=59)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('still')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'take' (original card_id=60)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('take')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'many' (original card_id=61)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('many')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'never' (original card_id=62)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-06', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('never')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'life' (original card_id=63)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-07', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('life')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'say' (original card_id=64)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-07', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('say')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'world' (original card_id=65)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-07', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('world')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'down' (original card_id=66)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-07', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('down')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'great' (original card_id=67)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-07', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('great')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'through' (original card_id=68)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-07', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('through')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'last' (original card_id=69)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-07', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('last')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'while' (original card_id=70)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-07', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('while')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'such' (original card_id=71)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-18', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('such')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'man' (original card_id=72)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-18', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('man')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'home' (original card_id=73)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-18', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('home')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'long' (original card_id=74)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-18', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('long')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'look' (original card_id=75)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-18', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('look')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'use' (original card_id=76)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-18', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('use')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'same' (original card_id=77)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-18', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('same')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'used' (original card_id=78)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-18', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('used')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'both' (original card_id=79)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-18', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('both')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'every' (original card_id=80)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-18', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('every')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- Word: 'part' (original card_id=81)
insert into vocab_progress (user_id, vocab_card_id, interval_days, easiness, repetitions, next_review_at, last_quality, times_seen, times_correct)
select :target_user_id, vc.id, 1, 2.6, 1, '2026-08-18', 5, 1, 1
from vocab_cards vc where lower(vc.word) = lower('part')
on conflict (user_id, vocab_card_id) do update set
  interval_days = excluded.interval_days,
  easiness = excluded.easiness,
  repetitions = excluded.repetitions,
  next_review_at = excluded.next_review_at,
  last_quality = excluded.last_quality,
  times_seen = excluded.times_seen,
  times_correct = excluded.times_correct;

-- ─── Study Sessions ───

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'VOCABULARY', '2026-07-13 13:29:03.735133', '2026-07-13 13:54:18.384102', 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'VOCABULARY', '2026-07-23 14:31:48.183650', NULL, 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'READING', '2026-07-23 14:31:51.577430', NULL, 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'LISTENING', '2026-07-23 14:31:53.263601', NULL, 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'WRITING', '2026-07-23 14:31:54.683703', NULL, 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'SPEAKING', '2026-07-23 14:31:55.163636', NULL, 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'VOCABULARY', '2026-07-23 15:17:26.482192', NULL, 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'READING', '2026-07-23 15:17:27.488036', NULL, 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'LISTENING', '2026-07-23 15:17:28.417892', NULL, 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'VOCABULARY', '2026-07-23 15:17:29.312179', '2026-07-23 15:42:43.530932', 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'READING', '2026-07-30 23:18:32.835357', '2026-07-30 23:18:44.778556', 0, 40, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'READING', '2026-07-30 23:18:50.013045', NULL, 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'LISTENING', '2026-07-30 23:18:52.748661', NULL, 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'READING', '2026-07-30 23:18:53.420506', NULL, 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'LISTENING', '2026-07-30 23:18:54.958648', NULL, 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'WRITING', '2026-07-30 23:18:57.758713', NULL, 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'SPEAKING', '2026-07-30 23:18:58.582142', NULL, 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'VOCABULARY', '2026-08-05 14:34:33.854815', NULL, 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'VOCABULARY', '2026-08-05 14:46:31.518124', NULL, 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'VOCABULARY', '2026-08-05 14:46:46.065384', NULL, 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'VOCABULARY', '2026-08-05 14:59:29.135032', NULL, 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'VOCABULARY', '2026-08-05 15:07:59.304003', NULL, 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'VOCABULARY', '2026-08-05 15:34:38.054261', NULL, 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'VOCABULARY', '2026-08-05 15:35:32.548488', '2026-08-05 15:35:58.242076', 100, 20, 20)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'READING', '2026-08-05 23:55:14.235586', NULL, 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'READING', '2026-08-05 23:55:21.292084', NULL, 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'READING', '2026-08-05 23:57:03.962781', NULL, 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'VOCABULARY', '2026-08-05 23:58:02.375915', NULL, 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'READING', '2026-08-05 23:58:04.072483', NULL, 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'LISTENING', '2026-08-05 23:58:05.240966', NULL, 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'WRITING', '2026-08-05 23:58:09.456861', NULL, 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'SPEAKING', '2026-08-05 23:58:10.176485', NULL, 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'VOCABULARY', '2026-08-06 13:35:24.333684', NULL, 0, 0, 0)
on conflict do nothing;

insert into study_sessions (user_id, session_type, started_at, ended_at, xp_earned, items_total, items_correct)
values (:target_user_id, 'VOCABULARY', '2026-08-17 12:28:22.479836', NULL, 0, 0, 0)
on conflict do nothing;
